# Generated by Django 6.1.1 on 2026-09-18 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('autor', models.CharField(max_length=200, verbose_name='autor')),
                ('anio', models.IntegerField(verbose_name='Año')),
                ('disponible', models.BooleanField(default=True, verbose_name='Disponible')),
            ],
        ),
    ]
